name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-logistic-model:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies using the Makefile
      - name: Install dependencies
        run: make install

      # Step 4: Run the logistic regression model and generate metrics
      - name: Run logistic model
        run: make run

      # Step 5: Add the Python application status badge to the README (if not already there)
      - name: Add status badge
        run: |
          if ! grep -q '![Python application]' README.md; then
            echo "![Python application](https://github.com/afbeltranr/ml-credit-elegibility/workflows/Python%20application/badge.svg)" >> README.md
          fi